import Foundation

enum ConsoleLanguage: String, CaseIterable, Identifiable {
    case system
    case english = "en"
    case chineseSimplified = "zh-Hans"
    case japanese = "ja"

    var id: String { rawValue }

    var localeIdentifier: String {
        switch self {
        case .system:
            return Locale.preferredLanguages.first ?? Locale.current.identifier
        case .english:
            return "en"
        case .chineseSimplified:
            return "zh-Hans"
        case .japanese:
            return "ja"
        }
    }

    var localizationCode: String? {
        switch self {
        case .system:
            return nil
        case .english:
            return "en"
        case .chineseSimplified:
            return "zh-Hans"
        case .japanese:
            return "ja"
        }
    }

    var displayName: String {
        switch self {
        case .system:
            return AppLocalization.string("language.system", fallback: "Follow System")
        case .english:
            return AppLocalization.string("language.english", fallback: "English")
        case .chineseSimplified:
            return AppLocalization.string("language.chinese_simplified", fallback: "简体中文")
        case .japanese:
            return AppLocalization.string("language.japanese", fallback: "日本語")
        }
    }
}

enum AppLocalization {
    static func string(_ key: String, fallback: String, _ arguments: CVarArg...) -> String {
        let language = ConsoleAppSettings.appLanguage
        let bundle = bundle(for: language)
        let format = NSLocalizedString(key, tableName: "Localizable", bundle: bundle, value: fallback, comment: "")
        guard arguments.isEmpty == false else {
            return format
        }
        return String(format: format, locale: Locale(identifier: language.localeIdentifier), arguments: arguments)
    }

    static var none: String {
        string("common.none", fallback: "None")
    }

    static var unknown: String {
        string("common.unknown", fallback: "Unknown")
    }

    static var yes: String {
        string("common.yes", fallback: "Yes")
    }

    static var no: String {
        string("common.no", fallback: "No")
    }

    static var missing: String {
        string("common.missing", fallback: "Missing")
    }

    static var stored: String {
        string("common.stored", fallback: "Stored")
    }

    static var keychainReady: String {
        string("common.keychain_ready", fallback: "Keychain ready")
    }

    static var missingNodeSecret: String {
        string("common.missing_node_secret", fallback: "Missing node_secret")
    }

    static var chooseConnectedNode: String {
        string("common.choose_connected_node", fallback: "Choose a connected node")
    }

    static func yesNo(_ value: Bool) -> String {
        value ? yes : no
    }

    static func phrase(_ english: String) -> String {
        switch ConsoleAppSettings.appLanguage {
        case .chineseSimplified:
            return zhHansExtraPhrases[english] ?? zhHansPhrases[english] ?? english
        case .japanese:
            return jaExtraPhrases[english] ?? jaPhrases[english] ?? english
        case .system:
            let preferred = Locale.preferredLanguages.first ?? Locale.current.identifier
            if preferred.hasPrefix("zh") {
                return zhHansExtraPhrases[english] ?? zhHansPhrases[english] ?? english
            }
            if preferred.hasPrefix("ja") {
                return jaExtraPhrases[english] ?? jaPhrases[english] ?? english
            }
            return english
        case .english:
            return english
        }
    }

    static func bountyText(_ text: String) -> String {
        localizedBountyText(text, target: resolvedDisplayLanguage)
    }

    static func bountyTerm(_ text: String?) -> String? {
        guard let text = text?.trimmingCharacters(in: .whitespacesAndNewlines),
              text.isEmpty == false else {
            return nil
        }
        return localizedBountyToken(text, target: resolvedDisplayLanguage)
    }

    static func hasBountyTranslation(for text: String) -> Bool {
        bountyText(text) != text
    }

    private static func bundle(for language: ConsoleLanguage) -> Bundle {
        guard let localizationCode = language.localizationCode,
              let path = Bundle.main.path(forResource: localizationCode, ofType: "lproj"),
              let bundle = Bundle(path: path) else {
            return .main
        }
        return bundle
    }

    private static var resolvedDisplayLanguage: ConsoleLanguage {
        switch ConsoleAppSettings.appLanguage {
        case .system:
            let preferred = Locale.preferredLanguages.first ?? Locale.current.identifier
            if preferred.hasPrefix("zh") {
                return .chineseSimplified
            }
            if preferred.hasPrefix("ja") {
                return .japanese
            }
            return .english
        case .english, .chineseSimplified, .japanese:
            return ConsoleAppSettings.appLanguage
        }
    }

    private static func localizedBountyText(_ text: String, target: ConsoleLanguage) -> String {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.isEmpty == false, target != .english else {
            return text
        }

        if let terms = bountyKnowledgeTerms(from: trimmed) {
            let prefix = target == .japanese ? "必要な知識：" : "需要知识："
            let separator = target == .japanese ? "、" : "、"
            let localizedTerms = terms.map { localizedBountyToken($0, target: target) }
            return prefix + localizedTerms.joined(separator: separator)
        }

        return localizedBountyToken(trimmed, target: target)
    }

    private static func bountyKnowledgeTerms(from text: String) -> [String]? {
        let lowercased = text.lowercased()
        let prefixes = ["knowledge needed:", "knowledge needed："]
        guard let prefix = prefixes.first(where: { lowercased.hasPrefix($0) }) else {
            return nil
        }

        return text
            .dropFirst(prefix.count)
            .split(separator: ",")
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { $0.isEmpty == false }
    }

    private static func localizedBountyToken(_ text: String, target: ConsoleLanguage) -> String {
        guard target != .english else {
            return text
        }

        let dictionary = target == .japanese ? jaBountyTerms : zhHansBountyTerms
        let normalized = normalizedBountyKey(text)
        if let exact = dictionary[normalized] {
            return exact
        }

        var result = text
            .replacingOccurrences(of: "_", with: " ")
            .replacingOccurrences(of: "-", with: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)

        for (source, translated) in dictionary.sorted(by: { $0.key.count > $1.key.count }) {
            guard source.contains(" ") else { continue }
            result = result.replacingOccurrences(of: source, with: translated, options: [.caseInsensitive])
        }
        return result
    }

    private static func normalizedBountyKey(_ text: String) -> String {
        text
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .lowercased()
            .replacingOccurrences(of: "_", with: " ")
            .replacingOccurrences(of: "-", with: " ")
            .split(whereSeparator: { $0.isWhitespace })
            .joined(separator: " ")
    }

    private static let zhHansBountyTerms: [String: String] = [
        "agent": "Agent",
        "api": "API",
        "are": "是",
        "asset": "资产",
        "beginner friendly": "适合新手",
        "bounty": "悬赏",
        "bounty task": "悬赏任务",
        "capsule": "Capsule",
        "compatibility": "兼容性",
        "data": "数据",
        "data compatibility": "数据兼容性",
        "external": "外部",
        "external task": "外部任务",
        "flink": "Flink",
        "graph": "图谱",
        "innovate": "创新",
        "knowledge": "知识",
        "matched asset": "匹配资产",
        "needed": "需要",
        "open": "开放",
        "question": "问题",
        "registry": "注册表",
        "schema": "Schema",
        "service": "服务",
        "skill": "技能",
        "sql": "SQL",
        "task": "任务",
        "trend analysis": "趋势分析",
        "trends": "趋势",
        "what": "什么",
        "workflow": "工作流",
    ]

    private static let jaBountyTerms: [String: String] = [
        "agent": "Agent",
        "api": "API",
        "are": "は",
        "asset": "アセット",
        "beginner friendly": "初心者向け",
        "bounty": "Bounty",
        "bounty task": "Bounty タスク",
        "capsule": "Capsule",
        "compatibility": "互換性",
        "data": "データ",
        "data compatibility": "データ互換性",
        "external": "外部",
        "external task": "外部タスク",
        "flink": "Flink",
        "graph": "グラフ",
        "innovate": "革新",
        "knowledge": "知識",
        "matched asset": "一致アセット",
        "needed": "必要",
        "open": "公開中",
        "question": "質問",
        "registry": "レジストリ",
        "schema": "スキーマ",
        "service": "サービス",
        "skill": "スキル",
        "sql": "SQL",
        "task": "タスク",
        "trend analysis": "トレンド分析",
        "trends": "トレンド",
        "what": "何",
        "workflow": "ワークフロー",
    ]

    private static let zhHansPhrases: [String: String] = [
        "Access": "访问",
        "Accepted": "已接受",
        "Accept Submission": "接受提交",
        "Action": "操作",
        "Actions": "操作",
        "Active tasks": "活跃任务",
        "API key": "API Key",
        "Archive Service": "归档服务",
        "Archived services leave the live marketplace feed and stop receiving new marketplace demand.": "归档后的服务会离开市场列表，并停止接收新的市场需求。",
        "Asset ID": "资产 ID",
        "Author": "作者",
        "Author node": "作者节点",
        "Avg response": "平均响应",
        "Base URL": "基础 URL",
        "Browse the EvoMap services marketplace to inspect live listings and manage your own offerings.": "浏览 EvoMap 服务市场，查看实时列表并管理你自己的服务。",
        "Browse the public Skill Store feed to inspect live metadata and version history.": "浏览公开 Skill Store，查看实时元数据和版本历史。",
        "Bundled characters": "打包字符数",
        "Bundled files": "打包文件",
        "Capabilities": "能力",
        "Category": "分类",
        "Characters": "字符数",
        "Commercials": "商业设置",
        "Completed order": "已完成订单",
        "Completion": "完成率",
        "Concurrency": "并发数",
        "Connection": "连接",
        "Created": "创建时间",
        "Credits": "积分",
        "Credits used": "已用积分",
        "Current order status": "当前订单状态",
        "Current visibility": "当前可见性",
        "Delete Forever": "永久删除",
        "Delete Version": "删除版本",
        "Delete this historical version?": "删除这个历史版本？",
        "Deleted": "删除时间",
        "Delete ready": "可删除",
        "Download": "下载",
        "Download cost": "下载成本",
        "Draft": "草稿",
        "Drafts": "草稿",
        "Edit Service": "编辑服务",
        "Edges": "边",
        "Entity": "实体",
        "Entity draft": "实体草稿",
        "Entries": "条目",
        "Errors": "错误",
        "Examples": "示例",
        "External file": "外部文件",
        "Feed": "信息流",
        "Final result": "最终结果",
        "Graph Manage": "图谱管理",
        "Graph Search": "图谱搜索",
        "Graph workspace": "图谱工作区",
        "Group": "分组",
        "Hub": "Hub",
        "ID": "ID",
        "Included bundle chars": "已包含打包字符数",
        "Key storage": "密钥存储",
        "Last publisher": "上次发布节点",
        "Last sync": "上次同步",
        "Limits": "限制",
        "Listing": "列表项",
        "Listing ID": "列表 ID",
        "Live performance": "实时表现",
        "Live request preview": "实时请求预览",
        "Loading": "加载中",
        "Managed folder": "托管目录",
        "Management": "管理",
        "Manage Graph": "管理图谱",
        "Marketplace": "市场",
        "Marketplace metadata": "市场元数据",
        "Matched nodes": "匹配节点",
        "Max concurrency": "最大并发",
        "Mode": "模式",
        "Move this Skill to the recycle bin?": "将这个技能移入回收站？",
        "Move to Recycle Bin": "移入回收站",
        "Name": "名称",
        "Never": "从未",
        "No accepted final asset has been recorded yet.": "尚未记录已接受的最终资产。",
        "No additional properties were returned for this node.": "此节点没有返回额外属性。",
        "No capabilities were returned for this service.": "此服务没有返回能力。",
        "No companion files discovered from the local skill directory.": "本地技能目录中未发现附加文件。",
        "No description was returned for this graph node.": "此图谱节点没有返回描述。",
        "No entity description yet.": "还没有实体描述。",
        "No public ratings are visible for this service yet.": "此服务暂无公开评分。",
        "No query has been submitted yet.": "尚未提交查询。",
        "No nodes matched the latest query.": "最新查询没有匹配节点。",
        "No relationships were returned for this node in the latest graph snapshot.": "最新图谱快照中没有返回此节点的关系。",
        "No service description is available.": "暂无服务描述。",
        "No submissions have been attached to this task yet.": "此任务尚未附加提交。",
        "No tags": "无标签",
        "No tags are available for this recycled Skill.": "此回收站技能暂无标签。",
        "No tags inferred yet.": "尚未推断出标签。",
        "No tags were published for this skill.": "此技能未发布标签。",
        "No validation findings yet.": "尚无校验问题。",
        "Node": "节点",
        "Node auth": "节点认证",
        "Node ID": "节点 ID",
        "Order metadata": "订单元数据",
        "Order this service": "订购此服务",
        "Original visibility": "原始可见性",
        "Organism": "Organism",
        "Permanent delete": "永久删除",
        "Permanent delete removes all versions, downloads, and metadata according to the official docs.": "根据官方文档，永久删除会移除所有版本、下载记录和元数据。",
        "Permanent delete ready": "可永久删除",
        "Place Order": "下单",
        "Plan": "计划",
        "Preview": "预览",
        "Price": "价格",
        "Price per task": "每任务价格",
        "Provider": "服务方",
        "Provider node": "服务方节点",
        "Public Skill Store": "公开 Skill Store",
        "Public ratings": "公开评分",
        "Publisher": "发布方",
        "Publisher node": "发布节点",
        "Queries": "查询",
        "Query": "查询",
        "Query price": "查询价格",
        "Query rate": "查询频率",
        "Rate Service": "评价服务",
        "Rating": "评分",
        "Rating draft": "评分草稿",
        "Rated": "已评分",
        "Rated at": "评分时间",
        "Ready": "就绪",
        "Recent ratings": "最近评分",
        "Recycle bin": "回收站",
        "Recipe": "Recipe",
        "Recommended sequence": "推荐序列",
        "Relation": "关系",
        "Related edges": "相关边",
        "Relationship": "关系",
        "Relationship draft": "关系草稿",
        "Request": "请求",
        "Requester node": "请求节点",
        "Restore": "恢复",
        "Restore ready": "可恢复",
        "Review": "审核",
        "Rollback target": "回滚目标",
        "Rollback ready": "可回滚",
        "Score": "得分",
        "Search": "搜索",
        "Search query": "搜索词",
        "Semantic Search": "语义搜索",
        "Selected listing": "选中列表项",
        "Selected node": "选中节点",
        "Selected order": "选中订单",
        "Selected skill": "选中技能",
        "Service": "服务",
        "Service management": "服务管理",
        "Skill ID": "技能 ID",
        "Skill Store Recycle Bin": "Skill Store 回收站",
        "Source": "来源",
        "Stars": "星级",
        "Status": "状态",
        "Store author": "商店作者",
        "Store enabled": "商店启用",
        "Store management": "商店管理",
        "Store metadata": "商店元数据",
        "Store snapshot": "商店快照",
        "Strategy": "策略",
        "Submit Rating": "提交评分",
        "Submitted": "提交时间",
        "Submissions": "提交数",
        "Tags": "标签",
        "Target": "目标",
        "Target version": "目标版本",
        "Task": "任务",
        "Task ID": "任务 ID",
        "The hub has not exposed a detailed timeline for this order yet.": "Hub 尚未暴露此订单的详细时间线。",
        "This cannot be undone from the recycle bin. Restoring first is safer if you might need it again.": "此操作无法从回收站撤销。如果之后可能还要用，先恢复更稳妥。",
        "This module stays deferred while the v1 node, skill, service, and order flows are being proven.": "在 v1 节点、技能、服务和订单流程验证完成前，此模块暂缓实现。",
        "Title": "标题",
        "Total": "总数",
        "Total published": "已发布总数",
        "Tracked tasks": "已追踪任务",
        "Tracking": "追踪",
        "Type": "类型",
        "Updated": "更新时间",
        "Usage": "用量",
        "Use cases": "使用场景",
        "Use the recycle bin to restore deleted Skills or permanently remove them.": "使用回收站恢复已删除技能，或将其永久移除。",
        "Version": "版本",
        "Versions": "版本数",
        "Visibility": "可见性",
        "Visibility ready": "可改可见性",
        "Visible listings": "可见列表",
        "Warnings": "警告",
        "Workspace": "工作区",
        "Write price": "写入价格",
        "Write rate": "写入频率",
        "Write status": "写入状态",
        "Writes": "写入",
    ]

    private static let zhHansExtraPhrases: [String: String] = [
        "Access & Pricing": "访问与定价",
        "Accountability": "责任追踪",
        "Ask the graph a natural-language question": "向图谱提出自然语言问题",
        "Cadence": "频率",
        "Capabilities (comma or newline separated)": "能力（逗号或换行分隔）",
        "Capsules": "Capsules",
        "Choose a skill to review metadata, limits, and publish readiness.": "选择一个技能以查看元数据、限制和发布准备状态。",
        "Claim URL": "认领链接",
        "Clusters": "集群",
        "Completed tasks": "已完成任务",
        "Create manual entity and relationship drafts for your Neo4j-backed personal knowledge graph. The current payload shape is kept tolerant because the public docs confirm `/kg/ingest` but do not show a full schema example.": "为你的 Neo4j 个人知识图谱创建手动实体和关系草稿。当前 payload 会保持兼容性，因为公开文档确认了 `/kg/ingest`，但没有给出完整 schema 示例。",
        "Description": "描述",
        "Dispatch": "调度",
        "Download to local library": "下载到本地库",
        "Downloads": "下载数",
        "Eligible": "符合条件",
        "Entity name": "实体名称",
        "Environment": "环境",
        "Estimated credits": "预计积分",
        "Execution timeline": "执行时间线",
        "Genes": "Genes",
        "Heartbeat": "心跳",
        "Heartbeat snapshot": "心跳快照",
        "Identifiers": "标识符",
        "Keep the first release focused. This area stays intentionally deferred while the main console shell is being proven.": "保持首版聚焦。在主控制台外壳验证完成前，这个区域会暂缓实现。",
        "Later module": "后续模块",
        "Local characters": "本地字符数",
        "Load `My Graph` to inspect the entities, assets, and relationships aggregated from your EvoMap activity.": "加载 `My Graph` 以查看从你的 EvoMap 活动聚合出的实体、资产和关系。",
        "Metadata": "元数据",
        "Model": "模型",
        "No node selected": "未选择节点",
        "No recycled skill selected": "未选择回收站技能",
        "No remote skill selected": "未选择远端技能",
        "No skill selected": "未选择技能",
        "No use cases were published for this service.": "此服务未发布使用场景。",
        "Node metadata": "节点元数据",
        "Node secret": "节点密钥",
        "Orders created from this app are tracked locally and refreshed from EvoMap task detail endpoints.": "从此应用创建的订单会在本地追踪，并通过 EvoMap 任务详情接口刷新。",
        "Overdue": "逾期",
        "Peers": "节点伙伴",
        "Penalty": "惩罚",
        "Pending events": "待处理事件",
        "Official docs allow `/a2a/skill/store/delete-version` only for historical versions; the current live version and the last remaining version stay protected.": "官方文档说明 `/a2a/skill/store/delete-version` 只能删除历史版本；当前线上版本和最后剩余版本会被保护。",
        "Official docs note that rollback sends the Skill back to `pending` review.": "官方文档说明回滚会让技能重新进入 `pending` 审核状态。",
        "Open Asset": "打开资产",
        "Open Final Asset": "打开最终资产",
        "Operator note": "操作说明",
        "Optional comment": "可选评论",
        "Properties": "属性",
        "Provider submissions": "服务方提交",
        "Publish": "发布",
        "Publish endpoint": "发布接口",
        "Publish target": "发布目标",
        "Published skills": "已发布技能",
        "Publishing to EvoMap": "正在发布到 EvoMap",
        "Quarantine": "隔离",
        "Rate this service": "评价此服务",
        "Raw payload preview": "原始 payload 预览",
        "Recipe ID (optional)": "Recipe ID（可选）",
        "Recommended execution sequence": "推荐执行序列",
        "Recycle-bin metadata": "回收站元数据",
        "Referral": "推荐码",
        "Relationships": "关系",
        "Remote skills": "远端技能",
        "Remote status": "远端状态",
        "Remote version": "远端版本",
        "Results": "结果",
        "Run natural-language queries against your personal EvoMap knowledge graph. Results can include matched entities, semantic clusters, and a recommended execution sequence.": "对你的个人 EvoMap 知识图谱运行自然语言查询。结果可以包含匹配实体、语义集群和推荐执行序列。",
        "Search summary": "搜索摘要",
        "Select a skill": "选择技能",
        "Sender ID": "Sender ID",
        "Skill Store": "Skill Store",
        "Skill Store action": "Skill Store 操作",
        "Skill workspace": "技能工作区",
        "Source entity name": "源实体名称",
        "Source preview": "源码预览",
        "Target entity name": "目标实体名称",
        "The latest query did not return a recommended sequence.": "最新查询没有返回推荐序列。",
        "The official docs say deleted Skills stay recoverable in the recycle bin for 30 days.": "官方文档说明删除的技能会在回收站保留 30 天，可恢复。",
        "This panel uses the official EvoMap service list, search, detail, publish, update, and archive endpoints from the live marketplace.": "此面板使用官方 EvoMap 服务市场的列表、搜索、详情、发布、更新和归档接口。",
        "This view uses the public Skill Store list, detail, and versions endpoints from the live EvoMap hub.": "此视图使用 EvoMap Hub 的公开 Skill Store 列表、详情和版本接口。",
        "Use cases (comma or newline separated)": "使用场景（逗号或换行分隔）",
        "Validation": "校验",
        "Version history": "版本历史",
        "What should this provider do?": "希望服务方做什么？",
        "Write preview": "写入预览",        "Anonymous buyer": "匿名买家",
        "Archive this service?": "归档此服务？",
        "Awaiting heartbeat data": "等待心跳数据",
        "Awaiting live heartbeat data": "等待实时心跳数据",
        "Character budget": "字符预算",
        "Choose one `SKILL.md` file.": "请选择一个 `SKILL.md` 文件。",
        "Cooldown": "冷却",
        "Current": "当前",
        "Downloaded": "已下载",
        "Enter a natural-language query to search your EvoMap knowledge graph.": "输入自然语言问题，搜索你的 EvoMap 知识图谱。",
        "Error": "错误",
        "Info": "信息",
        "Excluded": "已排除",
        "Featured": "精选",
        "Featured skill": "精选技能",
        "Imported preview": "导入预览",
        "Included": "已包含",
        "Load `My Graph` to inspect entities, assets, and relationships.": "加载 `我的图谱` 以查看实体、资产和关系。",
        "Loading Recycle Bin": "正在加载回收站",
        "Loading Skill Store": "正在加载 Skill Store",
        "Loading entitlement, pricing, and usage from `/kg/status`.": "正在从 `/kg/status` 加载权限、价格和用量。",
        "Loading marketplace detail": "正在加载市场详情",
        "Loading public ratings": "正在加载公开评分",
        "Loading recycled Skill Store entries for the selected node.": "正在加载选中节点的 Skill Store 回收站条目。",
        "Loading the live EvoMap services marketplace.": "正在加载 EvoMap 实时服务市场。",
        "Loading the public EvoMap Skill Store feed.": "正在加载公开 EvoMap Skill Store。",
        "Loading version history and detail": "正在加载版本历史和详情",
        "Loading your aggregated EvoMap knowledge graph from `/kg/my-graph`.": "正在从 `/kg/my-graph` 加载聚合后的 EvoMap 知识图谱。",
        "Local only": "仅本地",
        "Local rating": "本地评分",
        "Make Private": "设为私有",
        "Make Public": "设为公开",
        "Missing auth": "缺少认证",
        "Next heartbeat": "下次心跳",
        "No blocking validation errors.": "没有阻塞性校验错误。",
        "No changelog provided.": "未提供更新日志。",
        "No description is available for this recycled Skill.": "此回收站技能暂无描述。",
        "No locally tracked orders yet. Place an order from the Services module to start.": "尚无本地追踪订单。请先在服务模块下单。",
        "No preview text returned.": "未返回预览文本。",
        "No publisher selected": "未选择发布节点",
        "No recycled skills": "没有回收站技能",
        "No recycled skills match the current query.": "没有匹配当前搜索的回收站技能。",
        "No remote skills": "没有远端技能",
        "No remote skills are available yet.": "当前还没有远端技能。",
        "No remote skills match the current query.": "没有匹配当前搜索的远端技能。",
        "No services are visible yet.": "当前还没有可见服务。",
        "No services match the current query.": "没有匹配当前搜索的服务。",
        "Not eligible": "不符合条件",
        "Not published": "未发布",
        "Not rated yet": "尚未评分",
        "Not scheduled": "未安排",
        "Not yet": "尚未",
        "Not yet published": "尚未发布",
        "Offline": "离线",
        "Online": "在线",
        "Pause Service": "暂停服务",
        "Permanently delete this Skill?": "永久删除这个技能？",
        "Placing the live order on EvoMap and storing the returned task locally in Application Support.": "正在 EvoMap 上创建真实订单，并把返回任务保存到本地 Application Support。",
        "Provider pending": "服务方待定",
        "Published": "已发布",
        "Publishing the service listing to the live EvoMap marketplace.": "正在发布服务到 EvoMap 实时市场。",
        "Refreshing locally tracked orders from `/task/:id`.": "正在通过 `/task/:id` 刷新本地追踪订单。",
        "Refreshing task detail": "正在刷新任务详情",
        "Required fixes": "必修问题",
        "Resume Service": "恢复服务",
        "Run a query to load graph search results.": "运行查询以加载图谱搜索结果。",
        "Running a semantic query through `/kg/query`.": "正在通过 `/kg/query` 运行语义查询。",
        "Save a KG API key": "保存 KG API Key",
        "Save a paid Knowledge Graph API key in Settings before using `/kg/*` endpoints.": "使用 `/kg/*` 接口前，请先在设置中保存付费知识图谱 API Key。",
        "Saving the service update to the live EvoMap marketplace.": "正在把服务更新保存到 EvoMap 实时市场。",
        "Select a completed tracked order before rating the provider.": "请先选择一个已完成的追踪订单，再评价服务方。",
        "Select a connected node before placing an order.": "下单前请选择已连接节点。",
        "Select a connected node before publishing or updating a service.": "发布或更新服务前请选择已连接节点。",
        "Select a graph node": "选择图谱节点",
        "Select a recycled skill": "选择回收站技能",
        "Select a recycled skill and an authenticated node before permanently deleting.": "永久删除前请选择回收站技能和已认证节点。",
        "Select a recycled skill and an authenticated node before restoring.": "恢复前请选择回收站技能和已认证节点。",
        "Select a remote skill": "选择远端技能",
        "Select a remote skill and an authenticated node before changing visibility.": "更改可见性前请选择远端技能和已认证节点。",
        "Select a remote skill and an authenticated node before deleting.": "删除前请选择远端技能和已认证节点。",
        "Select a remote skill and an authenticated node before downloading.": "下载前请选择远端技能和已认证节点。",
        "Select a remote skill, an authenticated node, and a rollback target version.": "请选择远端技能、已认证节点和回滚目标版本。",
        "Select a service": "选择服务",
        "Select a service and an authenticated node before archiving it.": "归档前请选择服务和已认证节点。",
        "Select a service and an authenticated node before changing status.": "更改状态前请选择服务和已认证节点。",
        "Select a service and an authenticated node before placing an order.": "下单前请选择服务和已认证节点。",
        "Select a skill and a connected node to start publishing.": "请选择技能和已连接节点以开始发布。",
        "Select a tracked order": "选择追踪订单",
        "Select a tracked order before refreshing task detail.": "刷新任务详情前请选择追踪订单。",
        "Select the requester node before submitting a service rating.": "提交服务评分前请选择请求节点。",
        "The public Skill Store endpoint is disabled on this hub.": "此 Hub 已禁用公开 Skill Store 接口。",
        "The recycle bin is empty for the selected node.": "选中节点的回收站为空。",
        "This recycled Skill is no longer visible in the public Skill Store feed.": "这个回收站技能已不再出现在公开 Skill Store 中。",
        "This sends entity drafts as `entities[]` and relationship drafts as both `relationships[]` and `relations[]` for compatibility with the current public docs.": "这里会把实体草稿作为 `entities[]`，关系草稿同时作为 `relationships[]` 和 `relations[]` 发送，以兼容当前公开文档。",
        "Unknown date": "未知日期",
        "Unknown delete date": "未知删除日期",
        "Unknown node": "未知节点",
        "Unknown type": "未知类型",
        "Uses the Keychain-backed Knowledge Graph API key to call `/kg/status` directly from this Mac app.": "使用钥匙串中的知识图谱 API Key，从这个 Mac app 直接调用 `/kg/status`。",
        "Waiting for the EvoMap Skill Store response from the live publish request.": "正在等待 EvoMap Skill Store 对真实发布请求的响应。",
        "Writing entity and relationship drafts through `/kg/ingest`.": "正在通过 `/kg/ingest` 写入实体和关系草稿。",
        "Downloading the full `SKILL.md` bundle from the live EvoMap Skill Store.": "正在从线上 EvoMap Skill Store 下载完整 `SKILL.md` 包。",
        "Updating the Skill Store visibility on the live EvoMap hub.": "正在更新 EvoMap Hub 上的 Skill Store 可见性。",
        "Rolling the published Skill back to an earlier version on the live EvoMap hub.": "正在把已发布技能回滚到 EvoMap Hub 上的早期版本。",
        "Soft-deleting the Skill and moving it into the recycle bin.": "正在软删除技能并移入回收站。",
        "Restoring the Skill from the recycle bin on the live EvoMap hub.": "正在从 EvoMap Hub 回收站恢复技能。",
        "Permanently deleting the Skill and all recycle-bin metadata on the live EvoMap hub.": "正在从 EvoMap Hub 永久删除技能及所有回收站元数据。",
        "Loading recent public ratings from the live EvoMap marketplace.": "正在从 EvoMap 实时市场加载最近公开评分。",
        "Select a service to inspect recent public ratings.": "请选择服务以查看最近公开评分。",
        "Submitting the rating to `/a2a/service/rate` for this completed service order.": "正在为这个已完成服务订单提交 `/a2a/service/rate` 评分。",
        "Updating the service listing status on the live EvoMap marketplace.": "正在更新 EvoMap 实时市场中的服务状态。",
        "Archiving the service listing on the live EvoMap marketplace.": "正在归档 EvoMap 实时市场中的服务。",
        "Import a local `SKILL.md` file before publishing.": "发布前请先导入本地 `SKILL.md` 文件。",
        "Select a connected node as the Skill Store publisher.": "请选择已连接节点作为 Skill Store 发布方。",
        "The selected node is not eligible for Skill Store publishing yet.": "选中节点暂不符合 Skill Store 发布条件。",
        "Select a connected node to authenticate the Skill Store download.": "请选择已连接节点来认证 Skill Store 下载。",
        "Select a remote skill before downloading.": "下载前请选择远端技能。",
        "Select a remote skill before using Skill Store management actions.": "使用 Skill Store 管理操作前请选择远端技能。",
        "Select a connected node to authenticate Skill Store management actions.": "请选择已连接节点来认证 Skill Store 管理操作。",
        "Load the current version before rolling back.": "回滚前请先加载当前版本。",
        "No older versions are available for rollback.": "没有可用于回滚的旧版本。",
        "Choose an older version before requesting rollback.": "请求回滚前请选择旧版本。",
        "Choose an older version than the current live version.": "请选择比当前线上版本更旧的版本。",
        "The selected rollback target is no longer available.": "选中的回滚目标已不可用。",
        "Choose a historical version before deleting it.": "删除前请选择历史版本。",
        "Load the current live version before deleting history.": "删除历史版本前请先加载当前线上版本。",
        "The last remaining version cannot be deleted.": "不能删除最后剩余的版本。",
        "The current live version cannot be deleted.": "不能删除当前线上版本。",
        "The selected version is no longer available.": "选中的版本已不可用。",
        "Select a connected node before publishing services.": "发布服务前请选择已连接节点。",
        "Select a service before using marketplace management actions.": "使用市场管理操作前请选择服务。",
        "Select a connected node before managing services.": "管理服务前请选择已连接节点。",
        "Archived services cannot be paused or resumed.": "已归档服务不能暂停或恢复。",
        "This service is already archived.": "此服务已经归档。",
        "Enter a service title before publishing.": "发布前请输入服务标题。",
        "Enter a service description before publishing.": "发布前请输入服务描述。",
        "Add at least one capability before publishing.": "发布前请至少添加一项能力。",
        "Add at least one use case before publishing.": "发布前请至少添加一个使用场景。",
        "Price per task must be greater than zero.": "每任务价格必须大于 0。",
        "Max concurrency must be at least one.": "最大并发必须至少为 1。",
        "Load a service listing before updating it.": "更新前请先加载服务列表项。",
        "Select a connected node before updating this service.": "更新此服务前请选择已连接节点。",
        "Select a service before placing an order.": "下单前请选择服务。",
        "The selected node owns this service. Choose a different requester node.": "选中节点是此服务的所有者，请选择其他请求节点。",
        "Archived services cannot receive new orders.": "已归档服务不能接收新订单。",
        "The selected service does not have a valid listing identifier.": "选中服务没有有效的列表 ID。",
        "Load a service listing before placing an order.": "下单前请先加载服务列表项。",
        "Describe what you want the provider to do before placing an order.": "下单前请描述希望服务方做什么。",
        "Select a tracked order before rating the provider.": "评价服务方前请选择追踪订单。",
        "This tracked order is missing a service listing identifier.": "此追踪订单缺少服务列表 ID。",
        "Only completed orders can be rated.": "只有已完成订单可以评分。",
        "This order has already been rated locally.": "此订单已在本地评分。",
        "Load a completed order with a valid listing before rating this service.": "评分前请加载带有效列表 ID 的已完成订单。",
        "Service ratings must be between 1 and 5.": "服务评分必须在 1 到 5 之间。",
        "Add an entity or relationship draft before writing to the Knowledge Graph.": "写入知识图谱前请先添加实体或关系草稿。",
        "Enter an entity description before writing to the Knowledge Graph.": "写入知识图谱前请输入实体描述。",
        "Choose a source entity name before writing a relationship.": "写入关系前请选择源实体名称。",
        "Choose a target entity name before writing a relationship.": "写入关系前请选择目标实体名称。",
        "Select a tracked order before accepting a submission.": "接受提交前请选择追踪订单。",
        "The selected submission is missing an identifier.": "选中提交缺少 ID。",
        "This submission is already accepted.": "此提交已被接受。",
        "This order is already completed.": "此订单已完成。",
        "Expired orders cannot accept submissions.": "已过期订单不能接受提交。",
        "Select a connected node before opening the recycle bin.": "打开回收站前请选择已连接节点。",
        "Select a recycled skill before using recycle-bin actions.": "使用回收站操作前请选择回收站技能。",
        "Downloaded Skill": "已下载技能",
        "Updated Skill Visibility": "已更新技能可见性",
        "Published Service": "已发布服务",
        "Updated Service": "已更新服务",
        "Placed Service Order": "已创建服务订单",
        "Rated Service": "已评价服务",
        "Accepted Order Submission": "已接受订单提交",
        "Updated Service Status": "已更新服务状态",
        "Archived Service": "已归档服务",
        "Rolled Back Skill": "已回滚技能",
        "Deleted Skill Version": "已删除技能版本",
        "Deleted Skill": "已删除技能",
        "Restored Skill": "已恢复技能",
        "Permanently Deleted Skill": "已永久删除技能",
        "Skill publish failed": "技能发布失败",
        "Claim marked complete": "认领已标记完成",
        "Browser claim was confirmed by the user in this app.": "用户已在此应用中确认浏览器认领完成。",
        "Hello acknowledged": "Hello 已确认",
        "Heartbeat synced": "心跳已同步",
        "Accountability signal": "责任追踪信号",
        "Authenticated heartbeat could not be completed.": "认证心跳未能完成。",
        "Check the Hub endpoint and your local network.": "请检查 Hub 接口和本地网络。",
        "Store node_secret in Keychain before retrying.": "重试前请先把 node_secret 存入钥匙串。",
        "Heartbeat failed": "心跳失败",
        "Heartbeat skipped": "心跳已跳过",
        "Bearer auth is stored in Keychain.": "Bearer 认证已保存到钥匙串。",
        "Save the returned node_secret locally before sending heartbeat.": "发送心跳前请先在本地保存返回的 node_secret。",
        "Claim this node in the browser to bind it to your EvoMap account.": "请在浏览器中认领此节点，把它绑定到你的 EvoMap 账号。",
        "Claim is marked complete for this node.": "此节点已标记为认领完成。",
        "If the EvoMap claim page already showed success, mark this node as claimed locally; the public heartbeat docs do not expose a stable claim-state field yet.": "如果 EvoMap 认领页已经显示成功，请在本地把此节点标记为已认领；公开 heartbeat 文档目前还没有稳定暴露 claim-state 字段。",
        "Node is ready for authenticated follow-up requests.": "节点已可进行后续认证请求。",
        "Authenticated heartbeat is synced through `/a2a/heartbeat` using the Keychain-backed node_secret.": "已使用钥匙串中的 node_secret 通过 `/a2a/heartbeat` 同步认证心跳。",
        "Unnamed task": "未命名任务",
        "No payload details were returned.": "未返回 payload 详情。",
        "Primary Mac Node": "主 Mac 节点",
        "Staging Automation Node": "预发布自动化节点",
        "Archive Worker": "归档 Worker",
        "Main publishing node used for skill management and authenticated node polling.": "用于技能管理和认证节点轮询的主发布节点。",
        "This node is ready to publish or update skills.": "此节点已准备好发布或更新技能。",
        "Waiting for account claim confirmation before service publishing.": "发布服务前正在等待账号认领确认。",
        "Claim the node and clear the overdue staging task before the next publish.": "下次发布前请认领节点并清理逾期预发布任务。",
        "Account claim has not been completed.": "账号认领尚未完成。",
        "Claim the node first; staging publish remains blocked.": "请先认领节点；预发布发布仍被阻止。",
        "No node_secret found in the local Keychain.": "本地钥匙串中未找到 node_secret。",
        "Kept for reference while the new macOS console replaces older scripts.": "保留作参考，直到新的 macOS 控制台替代旧脚本。",
        "Safely inspect, stage, commit, push, and optionally open a draft PR.": "安全检查、暂存、提交、推送，并可选择打开草稿 PR。",
        "Latest Skill Store version is live.": "最新 Skill Store 版本已上线。",
        "Generate a local-first Japanese lesson video workflow with draft, TTS, and render stages.": "生成本地优先的日语课程视频流程，包含草稿、TTS 和渲染阶段。",
        "Remote update pending": "远端更新待处理",
        "This local draft differs from the published `0.9.0` version.": "此本地草稿与已发布的 `0.9.0` 版本不同。",
        "Published version `0.9.0` is still live.": "已发布的 `0.9.0` 版本仍在线。",
        "Internal draft for the EvoMap Console product and layout workflow.": "EvoMap Console 产品和布局工作流的内部草稿。",
        "Thin validation guidance": "校验指导较薄",
        "Add a dedicated validation section before this draft is publishable.": "发布此草稿前，请添加专门的校验章节。",
        "Japanese Learning Assistant": "日语学习助手",
        "Callable service for JLPT vocabulary explanation, grammar correction, example generation, and quiz drafting from a curated Japanese learning library.": "基于精选日语学习库，提供 JLPT 词汇解释、语法纠错、例句生成和测验草稿的可调用服务。",
        "Needs Fixes": "需要修复",
        "No description is available for this service.": "此服务暂无描述。",
        "Order created": "订单已创建",
        "Provider claimed the task": "服务方已领取任务",
        "Work began": "工作已开始",
        "Submission received": "已收到提交",
        "Order completed": "订单已完成",
        "Order expired": "订单已过期",
        "Warning": "警告",

    ]

    private static let jaPhrases: [String: String] = [
        "Access": "アクセス",
        "Accepted": "承認済み",
        "Accept Submission": "提出を承認",
        "Action": "操作",
        "Actions": "操作",
        "Active tasks": "稼働中タスク",
        "API key": "API Key",
        "Archive Service": "サービスをアーカイブ",
        "Archived services leave the live marketplace feed and stop receiving new marketplace demand.": "アーカイブ済みサービスはマーケットプレイスから外れ、新規需要を受け付けません。",
        "Asset ID": "アセット ID",
        "Author": "作者",
        "Author node": "作者ノード",
        "Avg response": "平均応答",
        "Base URL": "Base URL",
        "Browse the EvoMap services marketplace to inspect live listings and manage your own offerings.": "EvoMap サービスマーケットプレイスを閲覧し、公開中の一覧や自分のサービスを管理します。",
        "Browse the public Skill Store feed to inspect live metadata and version history.": "公開 Skill Store フィードでメタデータとバージョン履歴を確認します。",
        "Bundled characters": "同梱文字数",
        "Bundled files": "同梱ファイル",
        "Capabilities": "機能",
        "Category": "カテゴリ",
        "Characters": "文字数",
        "Commercials": "料金設定",
        "Completed order": "完了した注文",
        "Completion": "完了率",
        "Concurrency": "同時実行数",
        "Connection": "接続",
        "Created": "作成日時",
        "Credits": "クレジット",
        "Credits used": "使用クレジット",
        "Current order status": "現在の注文状態",
        "Current visibility": "現在の公開範囲",
        "Delete Forever": "完全に削除",
        "Delete Version": "バージョンを削除",
        "Delete this historical version?": "この履歴バージョンを削除しますか？",
        "Deleted": "削除日時",
        "Delete ready": "削除可能",
        "Download": "ダウンロード",
        "Download cost": "ダウンロード費用",
        "Draft": "ドラフト",
        "Drafts": "ドラフト",
        "Edit Service": "サービスを編集",
        "Edges": "エッジ",
        "Entity": "エンティティ",
        "Entity draft": "エンティティ下書き",
        "Entries": "件数",
        "Errors": "エラー",
        "Examples": "例",
        "External file": "外部ファイル",
        "Feed": "フィード",
        "Final result": "最終結果",
        "Graph Manage": "グラフ管理",
        "Graph Search": "グラフ検索",
        "Graph workspace": "グラフワークスペース",
        "Group": "グループ",
        "Hub": "Hub",
        "ID": "ID",
        "Included bundle chars": "同梱対象文字数",
        "Key storage": "キー保存",
        "Last publisher": "最終公開ノード",
        "Last sync": "最終同期",
        "Limits": "制限",
        "Listing": "リスティング",
        "Listing ID": "リスティング ID",
        "Live performance": "稼働実績",
        "Live request preview": "実リクエストプレビュー",
        "Loading": "読み込み中",
        "Managed folder": "管理フォルダ",
        "Management": "管理",
        "Manage Graph": "グラフを管理",
        "Marketplace": "マーケットプレイス",
        "Marketplace metadata": "マーケットプレイスメタデータ",
        "Matched nodes": "一致ノード",
        "Max concurrency": "最大同時実行",
        "Mode": "モード",
        "Move this Skill to the recycle bin?": "このスキルをゴミ箱に移動しますか？",
        "Move to Recycle Bin": "ゴミ箱に移動",
        "Name": "名前",
        "Never": "未実行",
        "No accepted final asset has been recorded yet.": "承認済みの最終アセットはまだ記録されていません。",
        "No additional properties were returned for this node.": "このノードには追加プロパティが返されていません。",
        "No capabilities were returned for this service.": "このサービスの機能は返されていません。",
        "No companion files discovered from the local skill directory.": "ローカルスキルディレクトリに付属ファイルは見つかりませんでした。",
        "No description was returned for this graph node.": "このグラフノードの説明は返されていません。",
        "No entity description yet.": "エンティティ説明はまだありません。",
        "No public ratings are visible for this service yet.": "このサービスの公開評価はまだありません。",
        "No query has been submitted yet.": "クエリはまだ送信されていません。",
        "No nodes matched the latest query.": "最新クエリに一致するノードはありません。",
        "No relationships were returned for this node in the latest graph snapshot.": "最新グラフスナップショットでこのノードの関係は返されていません。",
        "No service description is available.": "サービス説明はありません。",
        "No submissions have been attached to this task yet.": "このタスクにはまだ提出物がありません。",
        "No tags": "タグなし",
        "No tags are available for this recycled Skill.": "このゴミ箱内スキルにはタグがありません。",
        "No tags inferred yet.": "推定タグはまだありません。",
        "No tags were published for this skill.": "このスキルに公開タグはありません。",
        "No validation findings yet.": "検証指摘はまだありません。",
        "Node": "ノード",
        "Node auth": "ノード認証",
        "Node ID": "ノード ID",
        "Order metadata": "注文メタデータ",
        "Order this service": "このサービスを注文",
        "Original visibility": "元の公開範囲",
        "Organism": "Organism",
        "Permanent delete": "完全削除",
        "Permanent delete removes all versions, downloads, and metadata according to the official docs.": "公式ドキュメントによると、完全削除はすべてのバージョン、ダウンロード、メタデータを削除します。",
        "Permanent delete ready": "完全削除可能",
        "Place Order": "注文する",
        "Plan": "プラン",
        "Preview": "プレビュー",
        "Price": "価格",
        "Price per task": "タスク単価",
        "Provider": "提供者",
        "Provider node": "提供者ノード",
        "Public Skill Store": "公開 Skill Store",
        "Public ratings": "公開評価",
        "Publisher": "公開者",
        "Publisher node": "公開ノード",
        "Queries": "クエリ",
        "Query": "クエリ",
        "Query price": "クエリ価格",
        "Query rate": "クエリレート",
        "Rate Service": "サービスを評価",
        "Rating": "評価",
        "Rating draft": "評価ドラフト",
        "Rated": "評価済み",
        "Rated at": "評価日時",
        "Ready": "準備完了",
        "Recent ratings": "最近の評価",
        "Recycle bin": "ゴミ箱",
        "Recipe": "Recipe",
        "Recommended sequence": "推奨手順",
        "Relation": "関係",
        "Related edges": "関連エッジ",
        "Relationship": "関係",
        "Relationship draft": "関係ドラフト",
        "Request": "リクエスト",
        "Requester node": "依頼ノード",
        "Restore": "復元",
        "Restore ready": "復元可能",
        "Review": "レビュー",
        "Rollback target": "ロールバック先",
        "Rollback ready": "ロールバック可能",
        "Score": "スコア",
        "Search": "検索",
        "Search query": "検索語",
        "Semantic Search": "セマンティック検索",
        "Selected listing": "選択中のリスティング",
        "Selected node": "選択中のノード",
        "Selected order": "選択中の注文",
        "Selected skill": "選択中のスキル",
        "Service": "サービス",
        "Service management": "サービス管理",
        "Skill ID": "スキル ID",
        "Skill Store Recycle Bin": "Skill Store ゴミ箱",
        "Source": "ソース",
        "Stars": "星",
        "Status": "状態",
        "Store author": "ストア作者",
        "Store enabled": "ストア有効",
        "Store management": "ストア管理",
        "Store metadata": "ストアメタデータ",
        "Store snapshot": "ストアスナップショット",
        "Strategy": "戦略",
        "Submit Rating": "評価を送信",
        "Submitted": "提出日時",
        "Submissions": "提出数",
        "Tags": "タグ",
        "Target": "対象",
        "Target version": "対象バージョン",
        "Task": "タスク",
        "Task ID": "タスク ID",
        "The hub has not exposed a detailed timeline for this order yet.": "Hub はこの注文の詳細タイムラインをまだ公開していません。",
        "This cannot be undone from the recycle bin. Restoring first is safer if you might need it again.": "この操作はゴミ箱から元に戻せません。再利用の可能性がある場合は先に復元してください。",
        "This module stays deferred while the v1 node, skill, service, and order flows are being proven.": "v1 のノード、スキル、サービス、注文フローの検証中はこのモジュールを保留します。",
        "Title": "タイトル",
        "Total": "合計",
        "Total published": "公開合計",
        "Tracked tasks": "追跡中タスク",
        "Tracking": "追跡",
        "Type": "種類",
        "Updated": "更新日時",
        "Usage": "使用状況",
        "Use cases": "ユースケース",
        "Use the recycle bin to restore deleted Skills or permanently remove them.": "ゴミ箱から削除済みスキルを復元するか、完全に削除します。",
        "Version": "バージョン",
        "Versions": "バージョン数",
        "Visibility": "公開範囲",
        "Visibility ready": "公開範囲変更可能",
        "Visible listings": "表示中リスティング",
        "Warnings": "警告",
        "Workspace": "ワークスペース",
        "Write price": "書き込み価格",
        "Write rate": "書き込みレート",
        "Write status": "書き込み状態",
        "Writes": "書き込み",
    ]

    private static let jaExtraPhrases: [String: String] = [
        "Access & Pricing": "アクセスと料金",
        "Accountability": "責任管理",
        "Ask the graph a natural-language question": "グラフに自然言語で質問",
        "Cadence": "周期",
        "Capabilities (comma or newline separated)": "機能（カンマまたは改行区切り）",
        "Capsules": "Capsules",
        "Choose a skill to review metadata, limits, and publish readiness.": "メタデータ、制限、公開準備状況を確認するスキルを選択します。",
        "Claim URL": "登録 URL",
        "Clusters": "クラスタ",
        "Completed tasks": "完了タスク",
        "Create manual entity and relationship drafts for your Neo4j-backed personal knowledge graph. The current payload shape is kept tolerant because the public docs confirm `/kg/ingest` but do not show a full schema example.": "Neo4j ベースの個人ナレッジグラフ向けに、手動のエンティティと関係ドラフトを作成します。公開ドキュメントは `/kg/ingest` を確認していますが、完全な schema 例はないため、payload は互換性重視にしています。",
        "Description": "説明",
        "Dispatch": "ディスパッチ",
        "Download to local library": "ローカルライブラリへ保存",
        "Downloads": "ダウンロード数",
        "Eligible": "対象",
        "Entity name": "エンティティ名",
        "Environment": "環境",
        "Estimated credits": "推定クレジット",
        "Execution timeline": "実行タイムライン",
        "Genes": "Genes",
        "Heartbeat": "ハートビート",
        "Heartbeat snapshot": "ハートビートスナップショット",
        "Identifiers": "識別子",
        "Keep the first release focused. This area stays intentionally deferred while the main console shell is being proven.": "最初のリリースを集中させるため、この領域はメインコンソールが検証されるまで意図的に保留します。",
        "Later module": "後続モジュール",
        "Local characters": "ローカル文字数",
        "Load `My Graph` to inspect the entities, assets, and relationships aggregated from your EvoMap activity.": "`My Graph` を読み込み、EvoMap 活動から集約されたエンティティ、アセット、関係を確認します。",
        "Metadata": "メタデータ",
        "Model": "モデル",
        "No node selected": "ノード未選択",
        "No recycled skill selected": "ゴミ箱内スキル未選択",
        "No remote skill selected": "リモートスキル未選択",
        "No skill selected": "スキル未選択",
        "No use cases were published for this service.": "このサービスにはユースケースが公開されていません。",
        "Node metadata": "ノードメタデータ",
        "Node secret": "ノードシークレット",
        "Orders created from this app are tracked locally and refreshed from EvoMap task detail endpoints.": "このアプリで作成した注文はローカルで追跡され、EvoMap タスク詳細エンドポイントから更新されます。",
        "Overdue": "期限超過",
        "Peers": "ピア",
        "Penalty": "ペナルティ",
        "Pending events": "保留中イベント",
        "Official docs allow `/a2a/skill/store/delete-version` only for historical versions; the current live version and the last remaining version stay protected.": "公式ドキュメントでは `/a2a/skill/store/delete-version` は履歴バージョンのみ対象です。現在の公開版と最後に残る版は保護されます。",
        "Official docs note that rollback sends the Skill back to `pending` review.": "公式ドキュメントでは、ロールバックするとスキルは `pending` レビューに戻ります。",
        "Open Asset": "アセットを開く",
        "Open Final Asset": "最終アセットを開く",
        "Operator note": "オペレーター注記",
        "Optional comment": "任意コメント",
        "Properties": "プロパティ",
        "Provider submissions": "提供者の提出物",
        "Publish": "公開",
        "Publish endpoint": "公開エンドポイント",
        "Publish target": "公開先",
        "Published skills": "公開済みスキル",
        "Publishing to EvoMap": "EvoMap に公開中",
        "Quarantine": "隔離",
        "Rate this service": "このサービスを評価",
        "Raw payload preview": "Raw payload プレビュー",
        "Recipe ID (optional)": "Recipe ID（任意）",
        "Recommended execution sequence": "推奨実行手順",
        "Recycle-bin metadata": "ゴミ箱メタデータ",
        "Referral": "紹介コード",
        "Relationships": "関係",
        "Remote skills": "リモートスキル",
        "Remote status": "リモート状態",
        "Remote version": "リモート版",
        "Results": "結果",
        "Run natural-language queries against your personal EvoMap knowledge graph. Results can include matched entities, semantic clusters, and a recommended execution sequence.": "個人 EvoMap ナレッジグラフに自然言語クエリを実行します。結果には一致エンティティ、セマンティッククラスタ、推奨実行手順が含まれます。",
        "Search summary": "検索サマリー",
        "Select a skill": "スキルを選択",
        "Sender ID": "Sender ID",
        "Skill Store": "Skill Store",
        "Skill Store action": "Skill Store 操作",
        "Skill workspace": "スキルワークスペース",
        "Source entity name": "ソースエンティティ名",
        "Source preview": "ソースプレビュー",
        "Target entity name": "対象エンティティ名",
        "The latest query did not return a recommended sequence.": "最新クエリは推奨手順を返しませんでした。",
        "The official docs say deleted Skills stay recoverable in the recycle bin for 30 days.": "公式ドキュメントでは、削除されたスキルは 30 日間ゴミ箱から復元できます。",
        "This panel uses the official EvoMap service list, search, detail, publish, update, and archive endpoints from the live marketplace.": "このパネルは、公式 EvoMap サービスマーケットプレイスの一覧、検索、詳細、公開、更新、アーカイブエンドポイントを使用します。",
        "This view uses the public Skill Store list, detail, and versions endpoints from the live EvoMap hub.": "このビューは EvoMap Hub の公開 Skill Store 一覧、詳細、バージョンエンドポイントを使用します。",
        "Use cases (comma or newline separated)": "ユースケース（カンマまたは改行区切り）",
        "Validation": "検証",
        "Version history": "バージョン履歴",
        "What should this provider do?": "提供者に依頼する内容",
        "Write preview": "書き込みプレビュー",        "Anonymous buyer": "匿名購入者",
        "Archive this service?": "このサービスをアーカイブしますか？",
        "Awaiting heartbeat data": "ハートビートデータ待ち",
        "Awaiting live heartbeat data": "ライブハートビートデータ待ち",
        "Character budget": "文字数予算",
        "Choose one `SKILL.md` file.": "`SKILL.md` ファイルを 1 つ選択してください。",
        "Cooldown": "クールダウン",
        "Current": "現在",
        "Downloaded": "ダウンロード済み",
        "Enter a natural-language query to search your EvoMap knowledge graph.": "EvoMap ナレッジグラフを検索する自然言語クエリを入力します。",
        "Error": "エラー",
        "Info": "情報",
        "Excluded": "除外",
        "Featured": "注目",
        "Featured skill": "注目スキル",
        "Imported preview": "インポートプレビュー",
        "Included": "含める",
        "Load `My Graph` to inspect entities, assets, and relationships.": "`My Graph` を読み込み、エンティティ、アセット、関係を確認します。",
        "Loading Recycle Bin": "ゴミ箱を読み込み中",
        "Loading Skill Store": "Skill Store を読み込み中",
        "Loading entitlement, pricing, and usage from `/kg/status`.": "`/kg/status` から権限、料金、使用量を読み込み中。",
        "Loading marketplace detail": "マーケットプレイス詳細を読み込み中",
        "Loading public ratings": "公開評価を読み込み中",
        "Loading recycled Skill Store entries for the selected node.": "選択ノードの Skill Store ゴミ箱項目を読み込み中。",
        "Loading the live EvoMap services marketplace.": "EvoMap サービスマーケットプレイスを読み込み中。",
        "Loading the public EvoMap Skill Store feed.": "公開 EvoMap Skill Store フィードを読み込み中。",
        "Loading version history and detail": "バージョン履歴と詳細を読み込み中",
        "Loading your aggregated EvoMap knowledge graph from `/kg/my-graph`.": "`/kg/my-graph` から EvoMap ナレッジグラフを読み込み中。",
        "Local only": "ローカルのみ",
        "Local rating": "ローカル評価",
        "Make Private": "非公開にする",
        "Make Public": "公開する",
        "Missing auth": "認証なし",
        "Next heartbeat": "次回ハートビート",
        "No blocking validation errors.": "ブロックする検証エラーはありません。",
        "No changelog provided.": "変更履歴はありません。",
        "No description is available for this recycled Skill.": "このゴミ箱内スキルの説明はありません。",
        "No locally tracked orders yet. Place an order from the Services module to start.": "ローカル追跡注文はまだありません。Services から注文を作成してください。",
        "No preview text returned.": "プレビューテキストは返されていません。",
        "No publisher selected": "公開ノード未選択",
        "No recycled skills": "ゴミ箱内スキルなし",
        "No recycled skills match the current query.": "現在の検索に一致するゴミ箱内スキルはありません。",
        "No remote skills": "リモートスキルなし",
        "No remote skills are available yet.": "リモートスキルはまだありません。",
        "No remote skills match the current query.": "現在の検索に一致するリモートスキルはありません。",
        "No services are visible yet.": "表示可能なサービスはまだありません。",
        "No services match the current query.": "現在の検索に一致するサービスはありません。",
        "Not eligible": "対象外",
        "Not published": "未公開",
        "Not rated yet": "未評価",
        "Not scheduled": "未予定",
        "Not yet": "未実行",
        "Not yet published": "未公開",
        "Offline": "オフライン",
        "Online": "オンライン",
        "Pause Service": "サービスを一時停止",
        "Permanently delete this Skill?": "このスキルを完全に削除しますか？",
        "Placing the live order on EvoMap and storing the returned task locally in Application Support.": "EvoMap に実注文を作成し、返却タスクを Application Support に保存しています。",
        "Provider pending": "提供者未確定",
        "Published": "公開済み",
        "Publishing the service listing to the live EvoMap marketplace.": "EvoMap マーケットプレイスへサービスを公開中。",
        "Refreshing locally tracked orders from `/task/:id`.": "`/task/:id` からローカル追跡注文を更新中。",
        "Refreshing task detail": "タスク詳細を更新中",
        "Required fixes": "必要な修正",
        "Resume Service": "サービスを再開",
        "Run a query to load graph search results.": "クエリを実行してグラフ検索結果を読み込みます。",
        "Running a semantic query through `/kg/query`.": "`/kg/query` でセマンティッククエリを実行中。",
        "Save a KG API key": "KG API Key を保存",
        "Save a paid Knowledge Graph API key in Settings before using `/kg/*` endpoints.": "`/kg/*` エンドポイントを使う前に、設定で有料 Knowledge Graph API Key を保存してください。",
        "Saving the service update to the live EvoMap marketplace.": "EvoMap マーケットプレイスへサービス更新を保存中。",
        "Select a completed tracked order before rating the provider.": "提供者を評価する前に、完了済みの追跡注文を選択してください。",
        "Select a connected node before placing an order.": "注文前に接続済みノードを選択してください。",
        "Select a connected node before publishing or updating a service.": "サービスの公開または更新前に接続済みノードを選択してください。",
        "Select a graph node": "グラフノードを選択",
        "Select a recycled skill": "ゴミ箱内スキルを選択",
        "Select a recycled skill and an authenticated node before permanently deleting.": "完全削除の前にゴミ箱内スキルと認証済みノードを選択してください。",
        "Select a recycled skill and an authenticated node before restoring.": "復元前にゴミ箱内スキルと認証済みノードを選択してください。",
        "Select a remote skill": "リモートスキルを選択",
        "Select a remote skill and an authenticated node before changing visibility.": "公開範囲変更前にリモートスキルと認証済みノードを選択してください。",
        "Select a remote skill and an authenticated node before deleting.": "削除前にリモートスキルと認証済みノードを選択してください。",
        "Select a remote skill and an authenticated node before downloading.": "ダウンロード前にリモートスキルと認証済みノードを選択してください。",
        "Select a remote skill, an authenticated node, and a rollback target version.": "リモートスキル、認証済みノード、ロールバック先バージョンを選択してください。",
        "Select a service": "サービスを選択",
        "Select a service and an authenticated node before archiving it.": "アーカイブ前にサービスと認証済みノードを選択してください。",
        "Select a service and an authenticated node before changing status.": "状態変更前にサービスと認証済みノードを選択してください。",
        "Select a service and an authenticated node before placing an order.": "注文前にサービスと認証済みノードを選択してください。",
        "Select a skill and a connected node to start publishing.": "公開を始めるにはスキルと接続済みノードを選択してください。",
        "Select a tracked order": "追跡注文を選択",
        "Select a tracked order before refreshing task detail.": "タスク詳細更新前に追跡注文を選択してください。",
        "Select the requester node before submitting a service rating.": "サービス評価送信前に依頼ノードを選択してください。",
        "The public Skill Store endpoint is disabled on this hub.": "この Hub では公開 Skill Store エンドポイントが無効です。",
        "The recycle bin is empty for the selected node.": "選択ノードのゴミ箱は空です。",
        "This recycled Skill is no longer visible in the public Skill Store feed.": "このゴミ箱内スキルは公開 Skill Store フィードには表示されません。",
        "This sends entity drafts as `entities[]` and relationship drafts as both `relationships[]` and `relations[]` for compatibility with the current public docs.": "現在の公開ドキュメントとの互換性のため、エンティティ下書きを `entities[]`、関係下書きを `relationships[]` と `relations[]` の両方で送信します。",
        "Unknown date": "不明な日付",
        "Unknown delete date": "不明な削除日",
        "Unknown node": "不明なノード",
        "Unknown type": "不明な種類",
        "Uses the Keychain-backed Knowledge Graph API key to call `/kg/status` directly from this Mac app.": "Keychain に保存した Knowledge Graph API Key を使い、この Mac app から `/kg/status` を直接呼び出します。",
        "Waiting for the EvoMap Skill Store response from the live publish request.": "実公開リクエストへの EvoMap Skill Store 応答を待機中。",
        "Writing entity and relationship drafts through `/kg/ingest`.": "`/kg/ingest` でエンティティと関係の下書きを書き込み中。",
        "Downloading the full `SKILL.md` bundle from the live EvoMap Skill Store.": "ライブ EvoMap Skill Store から完全な `SKILL.md` バンドルをダウンロード中。",
        "Updating the Skill Store visibility on the live EvoMap hub.": "EvoMap Hub の Skill Store 公開範囲を更新中。",
        "Rolling the published Skill back to an earlier version on the live EvoMap hub.": "公開済みスキルを EvoMap Hub 上の以前のバージョンへロールバック中。",
        "Soft-deleting the Skill and moving it into the recycle bin.": "スキルをソフト削除してゴミ箱へ移動中。",
        "Restoring the Skill from the recycle bin on the live EvoMap hub.": "EvoMap Hub のゴミ箱からスキルを復元中。",
        "Permanently deleting the Skill and all recycle-bin metadata on the live EvoMap hub.": "EvoMap Hub からスキルとゴミ箱メタデータを完全削除中。",
        "Loading recent public ratings from the live EvoMap marketplace.": "EvoMap マーケットプレイスから最近の公開評価を読み込み中。",
        "Select a service to inspect recent public ratings.": "最近の公開評価を確認するサービスを選択してください。",
        "Submitting the rating to `/a2a/service/rate` for this completed service order.": "完了済みサービス注文へ `/a2a/service/rate` の評価を送信中。",
        "Updating the service listing status on the live EvoMap marketplace.": "EvoMap マーケットプレイスのサービス状態を更新中。",
        "Archiving the service listing on the live EvoMap marketplace.": "EvoMap マーケットプレイスのサービスをアーカイブ中。",
        "Import a local `SKILL.md` file before publishing.": "公開前にローカル `SKILL.md` をインポートしてください。",
        "Select a connected node as the Skill Store publisher.": "Skill Store 公開者として接続済みノードを選択してください。",
        "The selected node is not eligible for Skill Store publishing yet.": "選択ノードはまだ Skill Store 公開の対象外です。",
        "Select a connected node to authenticate the Skill Store download.": "Skill Store ダウンロード認証用の接続済みノードを選択してください。",
        "Select a remote skill before downloading.": "ダウンロード前にリモートスキルを選択してください。",
        "Select a remote skill before using Skill Store management actions.": "Skill Store 管理操作の前にリモートスキルを選択してください。",
        "Select a connected node to authenticate Skill Store management actions.": "Skill Store 管理操作を認証する接続済みノードを選択してください。",
        "Load the current version before rolling back.": "ロールバック前に現在のバージョンを読み込んでください。",
        "No older versions are available for rollback.": "ロールバック可能な古いバージョンはありません。",
        "Choose an older version before requesting rollback.": "ロールバック要求前に古いバージョンを選択してください。",
        "Choose an older version than the current live version.": "現在の公開版より古いバージョンを選択してください。",
        "The selected rollback target is no longer available.": "選択したロールバック先は利用できません。",
        "Choose a historical version before deleting it.": "削除前に履歴バージョンを選択してください。",
        "Load the current live version before deleting history.": "履歴削除前に現在の公開版を読み込んでください。",
        "The last remaining version cannot be deleted.": "最後に残るバージョンは削除できません。",
        "The current live version cannot be deleted.": "現在の公開版は削除できません。",
        "The selected version is no longer available.": "選択したバージョンは利用できません。",
        "Select a connected node before publishing services.": "サービス公開前に接続済みノードを選択してください。",
        "Select a service before using marketplace management actions.": "マーケットプレイス管理操作前にサービスを選択してください。",
        "Select a connected node before managing services.": "サービス管理前に接続済みノードを選択してください。",
        "Archived services cannot be paused or resumed.": "アーカイブ済みサービスは一時停止や再開ができません。",
        "This service is already archived.": "このサービスはすでにアーカイブ済みです。",
        "Enter a service title before publishing.": "公開前にサービスタイトルを入力してください。",
        "Enter a service description before publishing.": "公開前にサービス説明を入力してください。",
        "Add at least one capability before publishing.": "公開前に少なくとも 1 つの機能を追加してください。",
        "Add at least one use case before publishing.": "公開前に少なくとも 1 つのユースケースを追加してください。",
        "Price per task must be greater than zero.": "タスク単価は 0 より大きくしてください。",
        "Max concurrency must be at least one.": "最大同時実行数は 1 以上にしてください。",
        "Load a service listing before updating it.": "更新前にサービス一覧項目を読み込んでください。",
        "Select a connected node before updating this service.": "このサービス更新前に接続済みノードを選択してください。",
        "Select a service before placing an order.": "注文前にサービスを選択してください。",
        "The selected node owns this service. Choose a different requester node.": "選択ノードはこのサービスの所有者です。別の依頼ノードを選択してください。",
        "Archived services cannot receive new orders.": "アーカイブ済みサービスは新規注文を受け付けません。",
        "The selected service does not have a valid listing identifier.": "選択サービスには有効な一覧 ID がありません。",
        "Load a service listing before placing an order.": "注文前にサービス一覧項目を読み込んでください。",
        "Describe what you want the provider to do before placing an order.": "注文前に提供者へ依頼する内容を入力してください。",
        "Select a tracked order before rating the provider.": "提供者評価前に追跡注文を選択してください。",
        "This tracked order is missing a service listing identifier.": "この追跡注文にはサービス一覧 ID がありません。",
        "Only completed orders can be rated.": "完了済み注文のみ評価できます。",
        "This order has already been rated locally.": "この注文はローカルで評価済みです。",
        "Load a completed order with a valid listing before rating this service.": "評価前に有効な一覧を持つ完了済み注文を読み込んでください。",
        "Service ratings must be between 1 and 5.": "サービス評価は 1〜5 にしてください。",
        "Add an entity or relationship draft before writing to the Knowledge Graph.": "Knowledge Graph 書き込み前にエンティティまたは関係の下書きを追加してください。",
        "Enter an entity description before writing to the Knowledge Graph.": "Knowledge Graph 書き込み前にエンティティ説明を入力してください。",
        "Choose a source entity name before writing a relationship.": "関係を書き込む前にソースエンティティ名を選択してください。",
        "Choose a target entity name before writing a relationship.": "関係を書き込む前に対象エンティティ名を選択してください。",
        "Select a tracked order before accepting a submission.": "提出承認前に追跡注文を選択してください。",
        "The selected submission is missing an identifier.": "選択した提出物には ID がありません。",
        "This submission is already accepted.": "この提出物は承認済みです。",
        "This order is already completed.": "この注文はすでに完了しています。",
        "Expired orders cannot accept submissions.": "期限切れ注文は提出物を承認できません。",
        "Select a connected node before opening the recycle bin.": "ゴミ箱を開く前に接続済みノードを選択してください。",
        "Select a recycled skill before using recycle-bin actions.": "ゴミ箱操作前にゴミ箱内スキルを選択してください。",
        "Downloaded Skill": "スキルをダウンロード",
        "Updated Skill Visibility": "スキル公開範囲を更新",
        "Published Service": "サービスを公開",
        "Updated Service": "サービスを更新",
        "Placed Service Order": "サービス注文を作成",
        "Rated Service": "サービスを評価",
        "Accepted Order Submission": "注文提出を承認",
        "Updated Service Status": "サービス状態を更新",
        "Archived Service": "サービスをアーカイブ",
        "Rolled Back Skill": "スキルをロールバック",
        "Deleted Skill Version": "スキルバージョンを削除",
        "Deleted Skill": "スキルを削除",
        "Restored Skill": "スキルを復元",
        "Permanently Deleted Skill": "スキルを完全削除",
        "Skill publish failed": "スキル公開に失敗",
        "Claim marked complete": "登録完了としてマーク",
        "Browser claim was confirmed by the user in this app.": "ユーザーがこのアプリでブラウザ登録の完了を確認しました。",
        "Hello acknowledged": "Hello を確認",
        "Heartbeat synced": "ハートビート同期済み",
        "Accountability signal": "責任管理シグナル",
        "Authenticated heartbeat could not be completed.": "認証済みハートビートを完了できませんでした。",
        "Check the Hub endpoint and your local network.": "Hub エンドポイントとローカルネットワークを確認してください。",
        "Store node_secret in Keychain before retrying.": "再試行前に node_secret を Keychain に保存してください。",
        "Heartbeat failed": "ハートビート失敗",
        "Heartbeat skipped": "ハートビートをスキップ",
        "Bearer auth is stored in Keychain.": "Bearer 認証は Keychain に保存済みです。",
        "Save the returned node_secret locally before sending heartbeat.": "ハートビート送信前に返却された node_secret をローカル保存してください。",
        "Claim this node in the browser to bind it to your EvoMap account.": "ブラウザでこのノードを認証し、EvoMap アカウントに紐付けてください。",
        "Claim is marked complete for this node.": "このノードは登録完了としてマーク済みです。",
        "If the EvoMap claim page already showed success, mark this node as claimed locally; the public heartbeat docs do not expose a stable claim-state field yet.": "EvoMap の登録ページですでに成功表示が出ている場合は、このノードをローカルで登録済みとしてマークしてください。公開 heartbeat ドキュメントには安定した claim-state フィールドがまだありません。",
        "Node is ready for authenticated follow-up requests.": "ノードは後続の認証リクエストに対応できます。",
        "Authenticated heartbeat is synced through `/a2a/heartbeat` using the Keychain-backed node_secret.": "Keychain の node_secret を使って `/a2a/heartbeat` で認証済みハートビートを同期しました。",
        "Unnamed task": "無名タスク",
        "No payload details were returned.": "payload 詳細は返されていません。",
        "Primary Mac Node": "メイン Mac ノード",
        "Staging Automation Node": "ステージング自動化ノード",
        "Archive Worker": "アーカイブワーカー",
        "Main publishing node used for skill management and authenticated node polling.": "スキル管理と認証済みノードポーリングに使うメイン公開ノード。",
        "This node is ready to publish or update skills.": "このノードはスキル公開または更新の準備ができています。",
        "Waiting for account claim confirmation before service publishing.": "サービス公開前にアカウント認証確認を待っています。",
        "Claim the node and clear the overdue staging task before the next publish.": "次回公開前にノードを認証し、期限超過のステージングタスクを解消してください。",
        "Account claim has not been completed.": "アカウント認証が完了していません。",
        "Claim the node first; staging publish remains blocked.": "先にノードを認証してください。ステージング公開はブロックされています。",
        "No node_secret found in the local Keychain.": "ローカル Keychain に node_secret が見つかりません。",
        "Kept for reference while the new macOS console replaces older scripts.": "新しい macOS コンソールが旧スクリプトを置き換えるまで参照用に保持。",
        "Safely inspect, stage, commit, push, and optionally open a draft PR.": "安全に確認、ステージ、コミット、プッシュし、必要ならドラフト PR を開きます。",
        "Latest Skill Store version is live.": "最新の Skill Store バージョンが公開中です。",
        "Generate a local-first Japanese lesson video workflow with draft, TTS, and render stages.": "下書き、TTS、レンダー段階を持つ local-first 日本語レッスン動画ワークフローを生成します。",
        "Remote update pending": "リモート更新待ち",
        "This local draft differs from the published `0.9.0` version.": "このローカル下書きは公開済み `0.9.0` と異なります。",
        "Published version `0.9.0` is still live.": "公開済み `0.9.0` はまだ有効です。",
        "Internal draft for the EvoMap Console product and layout workflow.": "EvoMap Console 製品とレイアウトワークフローの内部下書き。",
        "Thin validation guidance": "検証ガイダンスが薄い",
        "Add a dedicated validation section before this draft is publishable.": "公開前に専用の検証セクションを追加してください。",
        "Japanese Learning Assistant": "日本語学習アシスタント",
        "Callable service for JLPT vocabulary explanation, grammar correction, example generation, and quiz drafting from a curated Japanese learning library.": "厳選した日本語学習ライブラリから JLPT 語彙説明、文法添削、例文生成、クイズ下書きを行う呼び出し可能サービス。",
        "Ready": "準備完了",
        "Needs Fixes": "修正が必要",
        "No description is available for this service.": "このサービスの説明はありません。",
        "Order created": "注文を作成",
        "Provider claimed the task": "提供者がタスクを取得",
        "Work began": "作業開始",
        "Submission received": "提出を受信",
        "Order completed": "注文完了",
        "Order expired": "注文期限切れ",
        "Warning": "警告",

    ]
}
