import Foundation

enum BountyWorkflowEngine {
    struct Input {
        var title: String
        var body: String?
        var rewardCredits: Int?
        var taskID: String
        var bountyID: String
        var currentDraft: String?
    }

    static func run(input: Input) -> BountyWorkflowResult {
        let body = input.body?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        if body.isEmpty {
            return .skipped(.missingBody)
        }

        let signals = detectSignals(title: input.title, body: body)
        let candidates = BountyTemplateCatalog.all()
            .map { template -> (BountyTemplate, BountyWorkflowMatch) in
                let match = score(template: template, title: input.title, body: body, signals: signals)
                return (template, match)
            }
            .sorted { $0.1.score > $1.1.score }

        guard let best = candidates.first else {
            return .skipped(.noTemplateMatch)
        }
        let (template, match) = best
        if match.score < BountyTemplateCatalog.nativeMinimumScore {
            return .skipped(.scoreBelowThreshold(match.score))
        }

        let context = BountyTemplateContext(
            title: input.title,
            body: body,
            rewardCredits: input.rewardCredits,
            taskID: input.taskID,
            bountyID: input.bountyID,
            detectedSignals: signals,
            currentDraft: input.currentDraft
        )
        let markdown = template.render(context)
        let answer = NativeBountyAnswer(
            markdown: markdown,
            templateID: template.id,
            templateTitle: template.title,
            signals: signals,
            matchScore: match.score,
            matchReasons: match.reasons,
            verificationNote: AppLocalization.string(
                "bounties.workflow.verification.native",
                fallback: "Generated by Console native workflow (template %@). Review before submission.",
                template.id
            )
        )
        return .answered(answer)
    }

    private static func score(
        template: BountyTemplate,
        title: String,
        body: String,
        signals: [String]
    ) -> BountyWorkflowMatch {
        let normalized = "\(title) \(body)".lowercased()
        var score = template.baseScore
        var reasons: [String] = []

        for signal in template.titleSignals where title.lowercased().contains(signal.lowercased()) {
            score += 12
            reasons.append("title:\(signal)")
        }
        for signal in template.bodySignals where body.lowercased().contains(signal.lowercased()) {
            score += 8
            reasons.append("body:\(signal)")
        }
        for signal in template.disqualifySignals where normalized.contains(signal.lowercased()) {
            score -= 50
            reasons.append("disqualify:\(signal)")
        }

        if body.count > 200 { score += 10 }
        if body.count > 800 { score += 10 }

        return BountyWorkflowMatch(
            templateID: template.id,
            templateTitle: template.title,
            score: score,
            reasons: reasons,
            signals: signals
        )
    }

    private static func detectSignals(title: String, body: String) -> [String] {
        let combined = "\(title) \(body)".lowercased()
        let candidates = [
            "swift", "python", "typescript", "javascript", "go", "rust", "java", "kotlin",
            "react", "swiftui", "uikit",
            "kafka", "flink", "spark", "rag", "llm", "openai", "anthropic", "claude", "gpt",
            "oauth", "auth", "jwt", "api", "rest", "graphql", "websocket", "grpc",
            "infra", "kubernetes", "docker", "aws", "gcp",
            "bug", "fix", "error", "exception", "crash", "leak",
            "design", "architecture", "schema", "migration", "pipeline",
        ]
        var found: [String] = []
        for candidate in candidates where combined.contains(candidate) {
            found.append(candidate)
            if found.count >= 8 { break }
        }
        return found
    }
}
